### ISSUE TITLE
No fading black effect when powers off/siege mode

### ISSUE THREAD

**Issue by SpartanGamezFTB** [amblelabs/ait#149] opened 2024-01-13 03:10 UTC
Version:
[1.1.37-1.20.1-beta](https://github.com/M-D-Team/ait-fabric-1.20.1/releases/tag/1.1.37-1.20.1-beta)

Issue:
When I turn the power off or enter siege mode, theres no fading black effect like there used to be. Once i click onto the monitor the lights come back. On older worlds and sometimes happens on newer worlds 

Video:
https://streamable.com/9m4rkv

**Comment by SpartanGamezFTB** [comment] 2024-01-13 03:20
works on a new world

**Comment by SpartanGamezFTB** [comment] 2024-01-13 04:22
nvm now it doesnt work

**Comment by SpartanGamezFTB** [comment] 2024-01-13 04:23
![image](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/39540379/c0aeb6c3-e797-4352-af51-e34d8b32e3a7)

**Comment by SpartanGamezFTB** [comment] 2024-01-13 11:20
once you click the monitor the lights essentially return

**Comment by SpartanGamezFTB** [comment] 2024-01-13 11:20
on older worlds this happens and when i sometimes on newer worlds when i just place a tardis sometimes its just dark even though the powers on untill ive clicked the monitor

**Comment by Monsterwaill** [comment] 2024-01-13 11:40
This is not a bug, but in fact a feature.

**Comment by Duzos** [comment] 2024-01-13 12:02
This is a bug you buggy bugger
Broken bc of @Creativious in progress rewrite
Should be fixed when hes one

**Comment by Loqor** [comment] 2024-01-15 01:03
In progress rewrite will fix.

**Closed as completed by Loqor** 2024-01-15 01:03 UTC
Labels: T: Bugfix
